# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1b7JQCfRo0E0xPATwbP8qztytnqXFKRbu
"""

username = input("Enter username: ")
password = input("Enter password: ")

if username == "admin" and password == "1234":
    print("login successful")
else:
    print("invalid credentials")

studmarks =  [45, 78, 90, 33, 60]

passs = 0
fail = 0

for score in studmarks:
    if score >= 50:
        passs += 1
    else:
        fail += 1

print("Total Students:", len(studmarks))
print("Passed Students:", passs)
print("Failed Students:", fail)

names = [" Alice ", "bob", " CHARLIE "]

clean = []

for name in names:
    cleaned_name = name.strip().lower()
    clean.append(cleaned_name)

print(clean)

messages = ["Hi", "Welcome to the platform", "OK"]

for message in messages:
    length = len(message)
    print("Message:", message)
    print("Length:", length)

    if length > 10:
        print("Message longer than 10 characters")

    print()

logs = ["INFO", "ERROR", "WARNING", "ERROR"]

error_count = 0

for log in logs:
    if log == "ERROR":
        error_count += 1

print("Total ERROR entries:", error_count)