# -*- coding: utf-8 -*-
"""Task2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MoasoYll0RcNjZdldK4wKggV6h8OW7xX

**1. Unique Words in a Sentence**
"""

#taking user input
sentence = input("Enter a sentence").lower()
#converting the sentence to words
words=sentence.split()
#removing the duplicates using set
unique_words=set(words)
print("Unique words count: ",len(unique_words))
print("Unique words: ",unique_words)

"""**2. Highest Salary from Employee Data**"""

employee_data={
    "Ram": 75000,
    "Shyam":80000,
    "Sita": 90000,
    "Meghana":85000,
    "Shreya": 70000,
    "Prajwal": 82000
    }
 #finding employee with highest salary
highest_employee=max(employee_data,key=employee_data.get)
highest_salary=employee_data[highest_employee]

print("Highest Salary:", highest_employee, "-", highest_salary)

"""**3. Find Maximum and Minimum Values**"""

numbers = [45, 22, 89, 10, 66]
max=numbers[0]
min=numbers[0]
#looping through the list to find out the min n max
for num in numbers:
  if num>max:
    max=num
    if num<min:
      min=num
print("List:",numbers)
print("Maximum Value:", max)
print("Minimum Value:", min)

"""**4. Count Products Above a Price Threshold**"""

#list of product prices
prices = [450, 1200, 899, 1500, 300, 500, 1250, 1500,2000]
count=0
#check each price
for price in prices:
  if price>1000:
    count+=1

print("Products above 1000:", count)

"""**5. Calculate Attendance Percentage**"""

attendance = ["P", "P", "A", "P", "P","A","P","P","A","P"]
#count present days
present_days=attendance.count("P")
#total days
total_days=len(attendance)
#percentage
percentage = (present_days / total_days) * 100
print("Attendance Percentage:", percentage)

"""**6. Remove Duplicate Phone Numbers**"""

phone_numbers = [9876543210, 9123456789, 9876543210]
#remove duplicates using set
unique_pnumbers=set(phone_numbers)
print("Unique Phone Number: ",unique_pnumbers)

"""**7. Count Character Frequency**"""

text=input("Enter a String: ")
char_count={}
#count characters
for char in text:
  if char in char_count:
    char_count[char]+=1
  else:
    char_count[char]=1
print(char_count)

"""**8. Convert List to Tuple**"""

numbers=[10,20,30,40]
number_tuple=tuple(numbers)
print("Tuple: ", number_tuple)

"""**9. Check if a Key Exists in a Dictionary**"""

employees = {
    "id": 101,
    "name": "Ravi",
    "salary": 50000
}

# Key to check
key = "name"

# Check if key exists
if key in employees:
    print("Employee exists")
else:
    print("Employee does not exist")

"""**10: Calculate Average Marks**"""

marks=[60,70,80,90,50,30,40]
#calculate average
average=sum(marks)/len(marks)
print("Average Marks: ",average)

